services:
  mariadb:
    image: mariadb:latest
    container_name: userDB
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: userdDB
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/ee0c33fcb01be9edfb07ad5c8e2262250940ea410fdb69ff8e928ab6ef8ddb54/_data
    healthcheck:
      test: mysqladmin -padmin ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  dropit:
    image: dropit:latest
    container_name: dropit
    restart: always
    build:
      dockerfile: dockerfile
    links: 
      - "mariadb:userdDB"
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 8080:8080
