services:
  mariadb:
    image: mariadb:latest
    container_name: userDB
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: userdDB
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - dropit:/app/sql

  dropit:
    image: dropit:latest
    container_name: dropit
    restart: always
    build:
      dockerfile: dockerfile
    links: 
      - "mariadb:userdDB"
    depends_on:
      mariadb:
        condition: service_started
    ports:
      - 8080:8080

volumes:
  dropit: