services:
  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: userdDB
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/da2c6f0bc2dc27271b500a2f6c7a2171e3ed4aa0808459b2c714a2a0ee9fc9b9/_data

  
  dropit:
    image: itsvictorfy/dropit:latest
    restart: always
    networks:
      - backend
    links: 
      - "mariadb:userdDB"
    depends_on:
      mariadb:
        condition: service_started
    ports:
      - 8080:8080

networks:
  backend:
    driver: bridge