apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropit-app-deployment
  labels:
    app: dropit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dropit-app
  template:
    metadata:
      labels:
        app: dropit-app
    spec:
      containers:
      - name: dropit
        image: docker.io/itsvictorfy/dropit:latest
        ports:
        - containerPort: 8080
