apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropit
  labels:
    app: dropit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dropit
  template:
    metadata:
      labels:
        app: dropit
    spec:
      containers:
      - name: dropit
        image: itsvictorfy/dropit:latest
        ports:
        - containerPort: 8080
